### ISSUE TITLE
 fatal error: chiabls/bls.hpp: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by DeanSparrow** [ZenyattaAbosom/Abosom#1]
This issue tracker is only for technical issues related to Abosom Core.

General Abosom questions and/or support requests and are best directed to the [Abosompay Reddit](https://www.reddit.com/r/abosompay/).

To report critical security issues, email infosec@abosompay.org instead of creating Github issues.

### Describe the issue
Wallet will not compile

#### If so, please list the steps to reproduce below:
1.Compile from source using guide in docs
2.
3.

### Expected behaviour
Wallet should compile using MAKE command

### Actual behaviour
bls/bls.h:14:27: fatal error: chiabls/bls.hpp: No such file or directory
compilation terminated.
Makefile:9223: recipe for target 'bls/libabosomconsensus_la-bls.lo' failed
make[2]: *** [bls/libabosomconsensus_la-bls.lo] Error 1

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Abosom Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: Ubuntu 
- CPU: 4 vcpu
- RAM: 8GB
- Disk size: 200GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by DeanSparrow** [comment]
Makefile is missing from Depends directory. Permissions also need to be updated. This fixes all issues to compile on Linux.

**Comment by ZenyattaAbosom** [comment]
Thankyou, We will make required changes.

**Comment by 86b** [comment]
https://github.com/ZenyattaAbosom/Abosom/pull/2

**Comment by ZenyattaAbosom** [comment]
Documentation has been updated to fix Chia issue and also outdated Wine reference.

Will close this now, Danke
